<?php

namespace AppBundle\Repository;

/**
 * NEORepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NEORepository extends \Doctrine\ORM\EntityRepository
{

    public function getHazardousNEO()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT neo FROM AppBundle\Entity\NEO neo WHERE neo.isHazardous = TRUE')
            ->getArrayResult();
    }

    public function getFastestNEO($hazardous = 0)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT neo FROM AppBundle\Entity\NEO neo WHERE neo.isHazardous = :hazardous ORDER BY neo.speed DESC')
            ->setParameter('hazardous', $hazardous)
            ->getArrayResult();
    }

    public function getBestYearNEO($hazardous = 0)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT SUBSTRING(neo.date, 1, 4) as year, COUNT(neo.id) as total FROM AppBundle\Entity\NEO neo WHERE neo.isHazardous = :hazardous GROUP BY year ORDER BY total DESC ')
            ->setMaxResults(1)
            ->setParameter('hazardous', $hazardous)
            ->getArrayResult();
    }

    public function getBestMonthNEO($hazardous = 0)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT SUBSTRING(neo.date, 6, 2) as month, COUNT(neo.id) as total FROM AppBundle\Entity\NEO neo WHERE neo.isHazardous = :hazardous GROUP BY month ORDER BY total DESC ')
            ->setMaxResults(1)
            ->setParameter('hazardous', $hazardous)
            ->getArrayResult();
    }
}
